module.exports = {
    GROUP_CHAT:"GROUP_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    PRIVATE_MESSAGE:"PRIVATE_MESSAGE"

}